[package]
name = "rss-sync"
version = "0.1.0"
edition = "2021"

[dependencies]
celery="0.5.3"
env_logger="0.10.0"
tokio = { version = "1.29.1", features = ["full"] }
structopt = "0.3"
serde = { version = "1.0.64", features = ["derive"] }
anyhow = "1.0.71"
async-trait = "0.1.71"
log = "0.4.0"